services:
  tfl-api:
    build: .
    container_name: tfl-api
    ports:
      - "30812:8000"
    restart: unless-stopped
    environment:
      - ROCKET_ENV=production
      - ROCKET_PORT=8000
      - ROCKET_ADDRESS=0.0.0.0
      - TFL_APP_ID=${TFL_APP_ID}
      - TFL_APP_KEY=${TFL_APP_KEY}
      - TFL_STOP_ID=${TFL_STOP_ID}
